### ISSUE TITLE
Add `baggageclaim` to reconfigure-pipelines

### ISSUE THREAD

**Issue by cirocosta** [concourse/ci#221] opened 2019-11-27 15:00 UTC
Hey,

We had a `baggageclaim` pipeline set in `ci.concourse-ci.org` (https://ci.concourse-ci.org/teams/main/pipelines/baggageclaim) which was being manually set from `baggageclaim`'s `ci` directory:

- https://github.com/concourse/baggageclaim/tree/4572464a21abb350e3d5566643dd0b3d07596bf5/ci

Given that these tests are currently not part of the main pipeline, it'd be great to have the pipeline automatically reconfigured by [`reconfigure-pipelines`](https://github.com/concourse/ci/blob/a59f75890e98f2fd4fd61d5483b39a851b9f83de/pipelines/reconfigure.yml).

thanks!

**Comment by pivotal-jamie-klassen** [comment] 2019-11-28 02:46
Did some preliminary investigation here, and when trying to run the [`unit-windows.yml`](https://github.com/concourse/baggageclaim/blob/master/ci/unit-windows.yml) task I've seen some errors like
```
C:\var\vcap\data\worker\work\containers\00003j7fdkc\tmp\build\cbb1dbfd\baggageclaim>ginkgo -r -p 
Failed to compile baggageclaim:

# github.com/DataDog/zstd
exec: "gcc": executable file not found in %PATH%
```
and it confused me a bit because as I understand it that worker should be provisioned by the [`install-windows-deps`](https://nci.concourse-ci.org/teams/main/pipelines/concourse/jobs/install-windows-deps) job, which installs the [`mingw`](https://github.com/concourse/ci/blob/master/pipelines/concourse.yml#L1457-L1459), chocolatey package, which is a port of gcc for Windows. So GCC has gotta be on that machine. So the only guess I have left is that the `PATH` for that task is configured in such a way that `gcc` can't be found - but then when I look at the old version of this job, why weren't we seeing this error before?

@kcmannem does this ring any bells from when zstd was first being introduced? I wonder if there was some snowflake configuration that got added to old prod's Windows worker.

**Comment by pivotal-jamie-klassen** [comment] 2019-11-28 13:44
FWIW I also searched for 'zstd' and 'windows' in the concourse/concourse and concourse/baggageclaim issues and PRs, as well as searching for 'windows' in Datadog/zstd. Today I reproduced the above error on old prod's windows worker, so I'm thinking I'll just bite the bullet and update the [`unit-windows.bat`](https://github.com/concourse/baggageclaim/blob/master/ci/scripts/unit-windows.bat) script to set the appropriately allowing `gcc` to be found by cgo. However now I'm hitting a new problem: I'm trying to get feedback on my changes to that script by running `fly execute` and uploading my local copy of the baggageclaim repo. When I look at the prod logs on papertrail, the web node reports [this block erroring](https://github.com/concourse/concourse/blob/master/atc/api/artifactserver/create.go#L62-L67) -- I'm assuming the source of the error is on the worker side, and logs from the windows VMs don't get forwarded to papertrail, as far as I can tell. So I'm going to try to figure out how to get bosh logs from a windows machine.

**Comment by pivotal-jamie-klassen** [comment] 2019-11-28 16:34
OK, so actually baggageclaim-related PRs are failing because our k8s nodes run on COS, which lacks the kernel modules required to run btrfs, and therefore the btrfs-related tests fail to mount volumes: https://nci.concourse-ci.org/teams/main/pipelines/prs/jobs/baggageclaim. I'm going to issue a PR to change the base image for the prod workers and PR workers to be based on ubuntu, which has the kernel modules we need.

**Comment by pivotal-jamie-klassen** [comment] 2019-11-29 00:31
While absently watching the baggageclaim pipeline run, I noticed it depends on an image `baggageclaim-ci`, which seems to be built by https://ci.concourse-ci.org/teams/main/pipelines/images/jobs/build-baggageclaim-ci -- it's probably worth pulling the image-building part into the `baggageclaim` pipeline itself so that it's a bit clearer what the dependencies are.

**Comment by pivotal-jamie-klassen** [comment] 2019-11-29 13:55
I spent some time getting the baggageclaim pipeline to build its own test-running image, and discovered that the [`Dockerfile`](https://github.com/concourse/baggageclaim/blob/master/Dockerfile) is broken in an interesting way. It has to do with a combination of dependencies:

* the `go:1` image on dockerhub and its underlying version of debian
* the `e2fslibs-dev` apt package versions available on that version of debian
* the way that `btrfs-progs` 4.15 uses those e2fs headers - see kdave/btrfs-progs#110

Since the last time [`build-baggageclaim-ci`](https://ci.concourse-ci.org/teams/main/pipelines/images/jobs/build-baggageclaim-ci/builds/142) ran in our old `images` pipeline, new versions of all these things have been released, and the versions being used in the old image are no longer supported in some cases.

I tried upgrading `btrfs-progs`, since kdave/btrfs-progs#110 has been fixed, but all versions after 4.16 require python and it felt like we were really starting to do a lot of work just to build that package. More on that later.

Then I tried downgrading `e2fslibs-dev` to 1.43, but apt complained that it didn't know about that version. That's because the last time our image was built we were using go 1.11, and the newest `go:1` image is 1.13, which is now based on a newer version of debian that no longer has `e2fslibs-dev` version 1.43 in its repositories.

So if we want to do this right, maybe we should depend on something like https://github.com/kdave/btrfs-progs/tree/master/ci/images to do the btrfs-progs building, so we don't have to fiddle around with all these dependencies when the development team already has that part figured out.

Honestly, maybe its worth highlighting in a more visible way (like via a resource) what version of btrfs we actually test baggageclaim against, because all the other big integration test suites use overlay, to the best of my knowledge (I suspect there's a topgun test that uses btrfs too, now that I think about it).

**Comment by cirocosta** [comment] 2019-11-29 15:35
> EDIT 2: I forgot to mention, but while testing out the changes on that branch doing fly execute against our new prod, uploading artifacts got a 500 on the first try almost every time.

I remember @vito also experiencing this - did you come to a conclusion, @vito ?

**Comment by pivotal-jamie-klassen** [comment] 2019-11-29 21:44
@cirocosta I think that issue is tracked in concourse/concourse#4621, but I'd definitely like to hear if @vito has any insights.

**Comment by kcmannem** [comment] 2019-11-29 22:02
is it just https://github.com/concourse/concourse/blob/master/atc/api/artifactserver/create.go#L39-L54

does the 500 happen every single time? or just the first try?

**Comment by pivotal-jamie-klassen** [comment] 2019-11-29 22:05
@kcmannem I remember looking at that comment, and peacefully allowing it to go right over my head. It's not every time - usually it would be the first (and potentially second and third) try, but it would always eventually succeed. I haven't bothered to think through why we would be more liable to hit that race condition on kubernetes.

**Comment by pivotal-jamie-klassen** [comment] 2019-11-30 21:36
OK, this is pretty much addressed by the combination of concourse/baggageclaim#33 and concourse/ci#226. The only remaining improvements I can think of right now are
* better resource icons in the baggageclaim pipeline
* slack notifications on either job

**Comment by pivotal-jamie-klassen** [comment] 2019-12-02 16:41
While thinking about sending slack notifications, we realized we need the `format-slack-message` task to be a bit more flexible to give better blame messages: concourse/ci#229

**Closed** 2019-12-05 12:10 UTC
